DROP DATABASE IF EXISTS eii;
CREATE DATABASE eii;
USE eii;

CREATE TABLE Alumno (
    IDAlumno INT AUTO_INCREMENT NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    FechaNacimiento DATE,
    Direccion VARCHAR(255),
    CONSTRAINT PK_ALUMNO PRIMARY KEY (IDAlumno)
);

CREATE TABLE Curso (
    IDCurso INT AUTO_INCREMENT,
    NombreCurso VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CURSO PRIMARY KEY (IDCurso)
);

CREATE TABLE Asignatura (
    IDAsignatura INT AUTO_INCREMENT NOT NULL,
    IDCurso INT NOT NULL,
    NombreAsignatura VARCHAR(100) NOT NULL,
    Semestre VARCHAR(100) NOT NULL,
    Creditos INT,
    CONSTRAINT CK_SEMESTRE CHECK (Semestre IN ('Primero', 'Segundo')),
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (IDAsignatura),
    CONSTRAINT FK_ASIGNATURA_CURSO FOREIGN KEY (IDCurso) REFERENCES Curso(IDCurso)
);

CREATE TABLE MatriculadoEn (
    IDAlumno INT,
    IDAsignatura INT,
    Nota INT,
    CONSTRAINT PK_MATRICULADOEN PRIMARY KEY (IDAlumno, IDAsignatura),
    CONSTRAINT FK_MATRICULADOEN_ALUMNO FOREIGN KEY (IDAlumno) REFERENCES Alumno(IDAlumno),
    CONSTRAINT FK_MATRICULADOEN_ASIGNATURA FOREIGN KEY (IDAsignatura) REFERENCES Asignatura(IDAsignatura)
);

CREATE TABLE Profesor (
    IDProfesor INT AUTO_INCREMENT,
    NombreProfesor VARCHAR(100) NOT NULL,
    correo VARCHAR(100),
    CONSTRAINT PK_PROFESOR PRIMARY KEY (IDProfesor)
);

CREATE TABLE Imparte (
    IDProfesor INT,
    IDAsignatura INT,
    CONSTRAINT PK_IMPARTE PRIMARY KEY (IDProfesor, IDAsignatura),
    CONSTRAINT FK_IMPARTE_PROFESOR FOREIGN KEY (IDProfesor) REFERENCES Profesor(IDProfesor),
    CONSTRAINT FK_IMPARTE_ASIGNATURA FOREIGN KEY (IDAsignatura) REFERENCES Asignatura(IDAsignatura)
);
